apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: keycloak-configs

resources:
- keycloak-operator.yaml
- keycloak-instance.yaml
- keycloak-db-secret.yaml
# rhdh-realm-import.yaml is gitignored (contains secrets)
# Copy from rhdh-realm-import.yaml.example and apply manually

commonLabels:
  config.openshift.io/component: keycloak
  config.openshift.io/managed-by: gitops
