apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: security-configs

resources:
- admin-rbac.yaml
- htpasswd-oauth.yaml
- htpasswd-secret.yaml

commonLabels:
  config.openshift.io/component: security
  config.openshift.io/managed-by: gitops
