apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: cluster-bootstrap-configs
  annotations:
    config.openshift.io/description: "OpenShift cluster bootstrap configurations"

resources:
# Storage configuration (includes LVM Storage, StorageClass, and Image Registry)
- storage/

# OpenShift GitOps operator
- gitops/

# Advanced Cluster Management (ACM)
- acm/

# Logging configurations
- logging/

# Security configurations (RBAC, authentication)
- security/

# Red Hat Developer Hub (Backstage)
- developer-hub/

# Red Hat Advanced Cluster Security (ACS/RHACS)
- acs/

# Keycloak (Red Hat build of Keycloak)
- keycloak/

commonLabels:
  config.openshift.io/bootstrap: "true"
  config.openshift.io/managed-by: gitops
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
