apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: argocd-applications

resources:
- developer-hub.yaml
# Add more applications here as needed:
# - storage.yaml
# - security.yaml
# - networking.yaml
