apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: storage-configs

resources:
- lvmstorage-operator.yaml
- lvmcluster.yaml

commonLabels:
  config.openshift.io/component: storage
  config.openshift.io/managed-by: gitops
