apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: logging-configs

resources:
- kubelet-log-rotation.yaml
- journald-retention.yaml

commonLabels:
  config.openshift.io/component: logging
  config.openshift.io/managed-by: gitops
