apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: node-configs

resources:
- kubelet-log-rotation.yaml
- journald-retention.yaml
- image-gc.yaml
- system-reserved.yaml

commonLabels:
  config.openshift.io/component: node-config
  config.openshift.io/managed-by: gitops
