apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: acm-configs

resources:
- acm-operator.yaml
- multiclusterhub.yaml

commonLabels:
  config.openshift.io/component: acm
  config.openshift.io/managed-by: gitops
