apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: gitops-configs

resources:
- gitops-operator.yaml
- argocd-instance.yaml
- argocd-secret-patch-job.yaml

labels:
- pairs:
    config.openshift.io/component: gitops
    config.openshift.io/managed-by: gitops
